### ISSUE TITLE
Additional documentation/guidance on how to customise this for different data sources?

### ISSUE THREAD

**Issue by feelec1** [awslabs/genai-bedrock-chatbot#4]
Hi, 
Not an issue but wanted to ask if there was any follow up documentation or guidance on how to use different data sources. For example I attempted to crawl a site and add this as a data source in Kendra, when I asked a question with information from the crawled site the orchestrator Lambda failed. Thanks in advance.

**Comment by jundongq** [comment]
Hi @feelec1, there are few potential reasons that the orchestrator Lambda can fail. Can you provide more details?

As for using different data sources for RAG use case, what you can do is to put the crawled data into this [kendra_documents folder](https://github.com/awslabs/genai-bedrock-chatbot/tree/main/assets/kendra_documents), then deploy the solution. The CDK stack will automatically [upload the new data sources to s3 bucket](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/code_stack.py#L227), and [create a kendra index](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/code_stack.py#L130) with the new data.

As for using different data sources for Data Query use case, you can put your structure data into this [folder](https://github.com/awslabs/genai-bedrock-chatbot/tree/main/assets/sagemaker_source), so the CDK deploy can upload the files to S3. Once this step is completed, you will need to go to AWS Glue page to manually trigger the Glue Crawler to generate the database and associated tables. After this step, you will need to update the [table details](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/lambda-container/sagemaker_pricing.py#L15), [SQL Prompt Template](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/lambda-container/prompt_templates.py#L32), and  [Response Template ](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/lambda-container/prompt_templates.py#L58) accordingly, to reflect the new database metadata.

In addition, you need to update the examples of [question intent classifier](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/lambda-container/app_question_intent.py#L23) to reflect your own use case.

Let me know if this helps.

**Comment by feelec1** [comment]
> Hi @feelec1, there are few potential reasons that the orchestrator Lambda can fail. Can you provide more details?
> 
> As for using different data sources for RAG use case, what you can do is to put the crawled data into this [kendra_documents folder](https://github.com/awslabs/genai-bedrock-chatbot/tree/main/assets/kendra_documents), then deploy the solution. The CDK stack will automatically [upload the new data sources to s3 bucket](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/code_stack.py#L227), and [create a kendra index](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/code_stack.py#L130) with the new data.
> 
> As for using different data sources for Data Query use case, you can put your structure data into this [folder](https://github.com/awslabs/genai-bedrock-chatbot/tree/main/assets/sagemaker_source), so the CDK deploy can upload the files to S3. Once this step is completed, you will need to go to AWS Glue page to manually trigger the Glue Crawler to generate the database and associated tables. After this step, you will need to update the [table details](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/lambda-container/sagemaker_pricing.py#L15), [SQL Prompt Template](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/lambda-container/prompt_templates.py#L32), and [Response Template ](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/lambda-container/prompt_templates.py#L58) accordingly, to reflect the new database metadata.
> 
> In addition, you need to update the examples of [question intent classifier](https://github.com/awslabs/genai-bedrock-chatbot/blob/49f2856bf0e8e950e2307fe71cc9ce7a0278795b/code/lambda-container/app_question_intent.py#L23) to reflect your own use case.
> 
> Let me know if this helps.

Thanks @jundongq , I did update them but I will run through it again and give it a go. Thanks for the information

**Comment by feelec1** [comment]
Hi @praveenflash 

I've tried to redeploy the solution with a few documents in the Kendra index and have synched these OK. I've also updated the app question intent to ensure that Use Case 1 is selected. 

When testing however I get the following error

`
[ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0)Traceback (most recent call last):  File "/var/task/genai_chatbot.py", line 21, in lambda_handler    output = get_response(query, session_id)  File "/var/task/index.py", line 31, in get_response    output = doc_retrieval(user_input)  File "/var/task/sagemaker_dg_rag.py", line 55, in doc_retrieval    web_link = source_link(s3_link)  File "/var/task/sagemaker_dg_rag.py", line 22, in source_link    res = json.loads(body)  File "/var/lang/lib/python3.11/json/__init__.py", line 346, in loads    return _default_decoder.decode(s)  File "/var/lang/lib/python3.11/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  File "/var/lang/lib/python3.11/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from None | [ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):   File "/var/task/genai_chatbot.py", line 21, in lambda_handler     output = get_response(query, session_id)   File "/var/task/index.py", line 31, in get_response     output = doc_retrieval(user_input)   File "/var/task/sagemaker_dg_rag.py", line 55, in doc_retrieval     web_link = source_link(s3_link)   File "/var/task/sagemaker_dg_rag.py", line 22, in source_link     res = json.loads(body)   File "/var/lang/lib/python3.11/json/__init__.py", line 346, in loads     return _default_decoder.decode(s)   File "/var/lang/lib/python3.11/json/decoder.py", line 337, in decode     obj, end = self.raw_decode(s, idx=_w(s, 0).end())   File "/var/lang/lib/python3.11/json/decoder.py", line 355, in raw_decode     raise JSONDecodeError("Expecting value", s, err.value) from None
-- | --
`

Does this mean that no related text in the Kendra index was found in relation to the question?

**Comment by feelec1** [comment]
@praveenflash do you have to have the source documents in the following format?

"url"
"Topic"
"Concent"

**Comment by praveenflash** [comment]
@feelec1 The source source documents are available as [Zip file](https://github.com/awslabs/genai-bedrock-chatbot/blob/main/assets/kendra_documents/sm_dg.zip) under assets folder. You can see the format of the documents there
